### ISSUE TITLE
Additional material

### ISSUE THREAD

**Issue by varunagarwal315** [iRayan7/startupschool19#1]
Hey thanks a lot for making this. Really helpful summary I can share with my team. This is another link to help startups handle financials and calculate their runway presented by Paul Graham in a blog a few years ago. Maybe you can just include it somewhere!

It is at `http://growth.tlb.org/` with github at `https://github.com/tlbtlbtlb/startuptools`

**Comment by iRayan7** [comment]
Hey @varunagarwal315, I'm glad to see that you liked the notes.

I have added the tool under [Startup Finance Pitfalls and How to Avoid Them](https://github.com/iRayan7/startupschool19/blob/master/README.md#startup-finance-pitfalls-and-how-to-avoid-them).

Please, let me know if you have any suggestions on improving the notes before I share it with others. Thanks 🙏
